import { Platform, StyleSheet } from 'react-native';
import { palette } from '../theme/theme';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.navy },

  toast: {
    position: 'absolute',
    left: 16,
    right: 16,
    zIndex: 50,
    backgroundColor: 'rgba(37, 99, 235, 0.95)',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 12,
  },
  toastText: {
    color: colors.white,
    fontWeight: '800',
    textAlign: 'center',
    fontSize: 14,
  },

  errorBanner: {
    position: 'absolute',
    left: 24,
    right: 24,
    zIndex: 20,
    ...(Platform.OS === 'android' ? { elevation: 18 as const } : {}),
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.35)',
  },
  errorBannerText: {
    color: '#FCA5A5',
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 13,
    writingDirection: 'rtl',
  },

  softRefreshBanner: {
    position: 'absolute',
    left: 24,
    right: 24,
    zIndex: 20,
    ...(Platform.OS === 'android' ? { elevation: 18 as const } : {}),
    backgroundColor: 'rgba(234, 179, 8, 0.12)',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: 'rgba(250, 204, 21, 0.35)',
  },
  softRefreshBannerText: {
    color: '#FDE68A',
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 12,
    writingDirection: 'rtl',
  },

  infoBanner: {
    position: 'absolute',
    left: 24,
    right: 24,
    zIndex: 20,
    ...(Platform.OS === 'android' ? { elevation: 18 as const } : {}),
    backgroundColor: 'rgba(37, 99, 235, 0.2)',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.35)',
  },
  infoBannerText: {
    color: '#BFDBFE',
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 12,
    writingDirection: 'rtl',
  },
  infoBannerCta: {
    color: colors.white,
    fontWeight: '800',
    textAlign: 'center',
    fontSize: 12,
    marginTop: 4,
    writingDirection: 'rtl',
  },
  fabColumn: {
    position: 'absolute',
    right: 12,
    zIndex: 12,
    alignItems: 'center',
    gap: 10,
  },
  fab: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: palette.hairlineStrong,
    backgroundColor: 'rgba(8,15,31,0.55)',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 10,
  },
  fabBusy: {
    opacity: 0.7,
  },

  listWrap: { ...StyleSheet.absoluteFillObject, paddingTop: 100 },

  topBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    zIndex: 10,
  },
  brandPill: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: palette.hairlineStrong,
    overflow: 'hidden',
    backgroundColor: 'rgba(8,15,31,0.4)',
  },
  brandDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: palette.live,
    shadowColor: palette.live,
    shadowOpacity: 0.7,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
  },
  brandCol: { alignItems: 'flex-end' },
  brandHe: { color: colors.white, fontSize: 19, fontWeight: '900', lineHeight: 22 },
  brandEn: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.5,
  },
  topRight: {
    alignItems: 'flex-end',
    gap: 8,
    maxWidth: 220,
    flexShrink: 1,
  },
  toggle: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: palette.hairlineStrong,
    overflow: 'hidden',
    backgroundColor: 'rgba(8,15,31,0.4)',
  },
  toggleText: { color: colors.electricBright, fontWeight: '800', fontSize: 13 },

  previewWrap: {
    position: 'absolute',
    left: 12,
    right: 12,
    zIndex: 15,
    alignItems: 'stretch',
  },
  previewCard: {
    backgroundColor: 'rgba(11, 20, 38, 0.96)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.55)',
    padding: 14,
    shadowColor: '#000',
    shadowOpacity: 0.45,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 18,
  },
  previewTop: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    gap: 12,
  },
  previewTextCol: { flex: 1, alignItems: 'flex-end' },
  previewCat: { color: colors.electricBright, fontWeight: '800', fontSize: 12 },
  previewQ: {
    color: colors.white,
    fontWeight: '800',
    fontSize: 16,
    marginTop: 4,
    textAlign: 'right',
    flexShrink: 1,
  },
  previewMeta: {
    color: colors.textSecondary,
    marginTop: 8,
    fontSize: 12,
    textAlign: 'right',
  },
  previewCtaRow: {
    marginTop: 12,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
    paddingTop: 10,
  },
  previewCta: { color: colors.electricBright, fontWeight: '800', fontSize: 14 },
  previewChevron: { color: colors.electricBright, fontSize: 22, fontWeight: '700' },
  previewDismiss: {
    alignSelf: 'center',
    marginTop: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  previewDismissText: { color: colors.textSecondary, fontWeight: '700', fontSize: 13 },

  selectedPointMarker: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(250, 204, 21, 0.95)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.95)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 8,
  },
  selectedPointInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.navy,
  },
});
