import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    maxHeight: '55%',
    backgroundColor: colors.navy,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: colors.bubbleBorder,
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -4 },
    elevation: 16,
  },
  handle: {
    alignSelf: 'center',
    width: 44,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.2)',
    marginTop: 10,
    marginBottom: 10,
  },
  headerBlock: {
    alignItems: 'flex-end',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
    marginBottom: 8,
  },
  titleRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'stretch',
  },
  title: {
    color: colors.white,
    fontSize: 17,
    fontWeight: '800',
    textAlign: 'right',
    writingDirection: 'rtl',
    flexShrink: 1,
  },
  subtitle: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 6,
    textAlign: 'right',
    alignSelf: 'stretch',
    lineHeight: 18,
    writingDirection: 'rtl',
    fontWeight: '600',
  },
  areaHint: {
    color: colors.textMuted,
    fontSize: 11,
    marginTop: 8,
    textAlign: 'right',
    alignSelf: 'stretch',
    lineHeight: 16,
    writingDirection: 'rtl',
    fontWeight: '600',
  },
  selectedPill: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.5)',
    backgroundColor: 'rgba(37, 99, 235, 0.18)',
    marginTop: 8,
  },
  selectedPillText: {
    color: colors.electricBright,
    fontSize: 12,
    fontWeight: '800',
    writingDirection: 'rtl',
  },
  ctaRow: {
    flexDirection: 'row-reverse',
    alignSelf: 'stretch',
    gap: 10,
    marginTop: 12,
  },
  ctaPrimary: {
    flex: 1,
  },
  ctaSecondary: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.bubbleBorder,
    backgroundColor: colors.bubble,
  },
  ctaSecondaryText: {
    color: colors.electricBright,
    fontWeight: '800',
    fontSize: 12,
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  refreshGhost: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 11,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.35)',
    backgroundColor: 'rgba(37, 99, 235, 0.1)',
  },
  refreshGhostText: { color: colors.electricBright, fontWeight: '700', fontSize: 11 },
  list: { flexGrow: 0 },
  emptyContainer: { flexGrow: 1, justifyContent: 'center' },
  empty: {
    color: colors.textMuted,
    textAlign: 'center',
    writingDirection: 'rtl',
    paddingVertical: 20,
    paddingHorizontal: 12,
    lineHeight: 20,
    fontSize: 14,
    fontWeight: '700',
  },
  row: { marginBottom: 10 },
  bubble: {
    backgroundColor: colors.bubble,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.bubbleBorder,
  },
  bubbleHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    marginBottom: 6,
    gap: 6,
  },
  catIcon: { fontSize: 14 },
  cat: {
    flex: 1,
    color: colors.electricBright,
    fontWeight: '800',
    fontSize: 12,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  verifiedPill: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(74, 222, 128, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(74, 222, 128, 0.35)',
  },
  verifiedPillText: {
    color: '#86EFAC',
    fontSize: 10,
    fontWeight: '800',
    writingDirection: 'rtl',
  },
  q: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'right',
    writingDirection: 'rtl',
    flexShrink: 1,
  },
  meta: {
    color: colors.textMuted,
    marginTop: 6,
    fontSize: 12,
    textAlign: 'right',
    writingDirection: 'rtl',
    fontWeight: '600',
  },
  freshLive: { color: '#86EFAC', fontWeight: '800' },
  freshFresh: { color: '#BBF7D0', fontWeight: '800' },
  freshStale: { color: '#FDE047', fontWeight: '800' },
  freshOutdated: { color: colors.textMuted, fontWeight: '800' },
});
